create table tb_belonging (position integer, list_id bigint not null, travel_id bigint not null, primary key (list_id, travel_id));
create table tb_travel (budget numeric(38,2), departure_date date, return_date date, id bigserial not null, accommodation varchar(255), destiny varchar(255), means_of_transport varchar(255), primary key (id));
create table tb_travel_list (id bigserial not null, name varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKa0mr028yqhiqd3wn12ay8cuor foreign key (list_id) references tb_travel_list;
alter table if exists tb_belonging add constraint FKes9c5uy6q6syc0taqjdu1wnfa foreign key (travel_id) references tb_travel;
INSERT INTO tb_travel_list (name) VALUES ('Internacional');
INSERT INTO tb_travel_list (name) VALUES ('Nacional');
INSERT INTO tb_travel (destiny, departure_date, return_date, means_of_transport, accommodation, budget) VALUES ('Salvador', '2023-12-31', '2024-02-15' , 'busao', 'hotel', 15000);
INSERT INTO tb_travel (destiny, departure_date, return_date, means_of_transport, accommodation, budget) VALUES ('Rio de janeiro', '2023-12-31', '2024-02-15' , 'busao', 'hotel', 18000);
INSERT INTO tb_travel (destiny, departure_date, return_date, means_of_transport, accommodation, budget) VALUES ('Australia', '2023-12-31', '2024-02-15' , 'aviao', 'hotel', 35000);
INSERT INTO tb_travel (destiny, departure_date, return_date, means_of_transport, accommodation, budget) VALUES ('Paris', '2023-12-31', '2024-02-15' , 'aviao', 'hotel', 35000);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (2, 3, 2);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (2, 4, 3);
